### ISSUE TITLE
Header Issue - Search Page

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#175]
#44 

Kristi Scholfield tested in Chrome and here were the results:

Kristi Scholfield tested in Chrome and here were the results:
![image](https://cloud.githubusercontent.com/assets/14330996/10696409/3d2cb9be-796d-11e5-8af8-5a3fd7824ee0.png)

**Comment by mbr4nt** [comment]
@tucaz , please fix the breadcrumbs and remove the extra menu items, then assing to Felipe for layout fixes.

**Comment by tucaz** [comment]
Fixed in QA

**Comment by felipebbtoledo** [comment]
Look and feel fixes are done. The main menu still shows duplicated items "Resouce Centers" and "Contact Us"

**Comment by tucaz** [comment]
Items removed from the menu.
