### ISSUE TITLE
Messenger Image Dimensions Inconsistent

### ISSUE THREAD

**Issue by SorensenK** [Allsteel/hni-textiles-webcomponents#221]
Messenger fabric thumbnail sizes are covering names and not the same

![image](https://cloud.githubusercontent.com/assets/15238848/10768755/a82a5b40-7cb0-11e5-9755-5ac74914ceb5.png)

**Comment by mbr4nt** [comment]
fixed

**Comment by SorensenK** [comment]
still having this issue, cleared cache and tried to refresh but no luck. I had someone else test it independently and they had the same result.

![image](https://cloud.githubusercontent.com/assets/15238848/10770652/6a5786d0-7cba-11e5-92a3-52ed0e3a4310.png)

**Comment by SorensenK** [comment]
passed in Chrome.
